### ISSUE TITLE
공통 컴포넌트 만들기

### ISSUE THREAD

**Issue by lulla-by** [movie-dog/movie-dog#1]
- 공통 컴포넌트 작업
- 정현 : input, input-search, selectbox, tag
- 예솔 : button, button-circle, page-number

**Comment by hardy-is-cat** [comment]
- Input 컴포넌트 생성 중 global-styles 수정(input, button dispaly와 폰트 설정), 프리티어 설정 수정

**Comment by hardy-is-cat** [comment]
- SearchBar 컴포넌트 생성 중 global-styles 수정(a11y-hidden 클래스 추가)
